# This rule is not used by the project security-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the security.ctem.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: security-operator
    app.kubernetes.io/managed-by: kustomize
  name: securityagent-editor-role
rules:
- apiGroups:
  - security.ctem.io
  resources:
  - securityagents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.ctem.io
  resources:
  - securityagents/status
  verbs:
  - get
